### ISSUE TITLE
how to change extra_host_config in jupyter_config

### ISSUE THREAD

**Issue by zonca** [compmodels/jupyterhub#5]
I am testing `swarmspawner.py`, it works great, I had only to customize the parsing of the docker info at:

https://github.com/compmodels/jupyterhub/blob/master/swarmspawner.py#L32

however it looks like I cannot change the memory limit from `jupyterhub_config.py`. I tried using either `c.DockerSpawner.extra_host_config = {"mem_limit" : "300m"}` or `c.SwarmSpawner.extra_host_config` without success.

**Comment by jhamrick** [comment]
I believe it is no longer necessary to use `SwarmSpawner` -- `DockerSpawner` should work out of the box with swarm now! See: https://github.com/jupyterhub/dockerspawner/pull/54#issuecomment-184873543

`SwarmSpawner` is also pretty out of date at this point which is probably why it's not working -- it looks like `extra_host_config` is configurable in DockerSpawner, but the line the loads the defaults in DockerSpawner (https://github.com/jupyterhub/dockerspawner/blob/master/dockerspawner/dockerspawner.py#L380) isn't present in SwarmSpawner, so that's probably the issue.

**Comment by zonca** [comment]
I didn't know that `DockerSpawner` supported Swarm! that's great news, thanks
